# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('proj_cl', models.CharField(max_length=20)),
                ('seed', models.CharField(max_length=20)),
                ('dut_ana_log', models.CharField(max_length=200)),
                ('dut_ana_status', models.CharField(max_length=20)),
                ('dut_ana_error', models.CharField(max_length=1000)),
                ('tb_ana_log', models.CharField(max_length=200)),
                ('tb_ana_status', models.CharField(max_length=20)),
                ('tb_ana_error', models.CharField(max_length=1000)),
                ('elab_log', models.CharField(max_length=200)),
                ('elab_status', models.CharField(max_length=20)),
                ('elab_error', models.CharField(max_length=1000)),
                ('simu_log', models.CharField(max_length=200)),
                ('simu_status', models.CharField(max_length=20)),
                ('simu_error', models.CharField(max_length=1000)),
                ('comp_cpu_time', models.CharField(max_length=20)),
                ('simu_cpu_time', models.CharField(max_length=20)),
                ('simu_time', models.CharField(max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regr.Case')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regr.Group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regr.Module')),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regr.Proj')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regr.User'),
        ),
        migrations.AddField(
            model_name='proj',
            name='dleader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dleader_fk', to='regr.User'),
        ),
        migrations.AddField(
            model_name='proj',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_fk', to='regr.User'),
        ),
        migrations.AddField(
            model_name='proj',
            name='vleader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vleader_fk', to='regr.User'),
        ),
        migrations.AddField(
            model_name='module',
            name='downer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downer_fk', to='regr.User'),
        ),
        migrations.AddField(
            model_name='module',
            name='vowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vowner_fk', to='regr.User'),
        ),
        migrations.AddField(
            model_name='case',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regr.User'),
        ),
    ]
