# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Simv',
        ),
        migrations.RenameField(
            model_name='sim',
            old_name='group',
            new_name='simv',
        ),
    ]
