# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DcChkDsgGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('log_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DcChkDsgRpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.DcChkDsgGroup')),
            ],
        ),
        migrations.CreateModel(
            name='DcClkGateRpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clk_gate', models.IntegerField()),
                ('gate_reg', models.IntegerField()),
                ('ugate_reg', models.IntegerField()),
                ('total_reg', models.IntegerField()),
                ('log_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DcError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=2000)),
                ('log_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DcPowerRpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib', models.CharField(max_length=100)),
                ('internal', models.CharField(max_length=50)),
                ('switching', models.CharField(max_length=50)),
                ('leakage', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('log_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DcQorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('log_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DcQorRpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.DcQorGroup')),
            ],
        ),
        migrations.CreateModel(
            name='DcRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('m_name', models.CharField(max_length=20)),
                ('clock', models.CharField(max_length=20)),
                ('cpu_time', models.CharField(max_length=20)),
                ('run_time', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DcTimeRpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_point', models.CharField(max_length=500)),
                ('end_point', models.CharField(max_length=500)),
                ('slack', models.FloatField()),
                ('log_path', models.CharField(max_length=500)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.DcRun')),
            ],
        ),
        migrations.CreateModel(
            name='DcWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=2000)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('line_number', models.CharField(blank=True, max_length=50, null=True)),
                ('log_path', models.CharField(max_length=500)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.DcRun')),
            ],
        ),
        migrations.CreateModel(
            name='FmRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('m_name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('run_time', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MpRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('m_name', models.CharField(max_length=20)),
                ('run_time', models.DateTimeField()),
                ('pj_props', django.contrib.postgres.fields.jsonb.JSONField()),
                ('props', django.contrib.postgres.fields.jsonb.JSONField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegrCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegrSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('end_date', models.DateTimeField(verbose_name='date ended')),
                ('p_name', models.CharField(max_length=20)),
                ('m_name', models.CharField(max_length=20)),
                ('v_name', models.CharField(max_length=20)),
                ('c_name', models.CharField(max_length=100)),
                ('proj_cl', models.CharField(max_length=20)),
                ('seed', models.CharField(max_length=20)),
                ('dut_ana_log', models.CharField(max_length=200)),
                ('dut_ana_status', models.CharField(max_length=20)),
                ('dut_ana_error', models.CharField(max_length=1000)),
                ('tb_ana_log', models.CharField(max_length=200)),
                ('tb_ana_status', models.CharField(max_length=20)),
                ('tb_ana_error', models.CharField(max_length=1000)),
                ('elab_log', models.CharField(max_length=200)),
                ('elab_status', models.CharField(max_length=20)),
                ('elab_error', models.CharField(max_length=1000)),
                ('simu_log', models.CharField(max_length=200)),
                ('simu_status', models.CharField(max_length=20)),
                ('simu_error', models.CharField(max_length=1000)),
                ('comp_cpu_time', models.CharField(max_length=20)),
                ('simu_cpu_time', models.CharField(max_length=20)),
                ('simu_time', models.CharField(max_length=20)),
                ('regr_types', models.CharField(max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.RegrCase')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.Module')),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.Proj')),
            ],
        ),
        migrations.CreateModel(
            name='RegrSimv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='regrsim',
            name='simv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.RegrSimv'),
        ),
        migrations.AddField(
            model_name='regrsim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.User'),
        ),
        migrations.AddField(
            model_name='regrcase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pj_app.User'),
        ),
        migrations.AddField(
            model_name='proj',
            name='dleader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dleader_fk', to='pj_app.User'),
        ),
        migrations.AddField(
            model_name='proj',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_fk', to='pj_app.User'),
        ),
        migrations.AddField(
            model_name='proj',
            name='vleader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vleader_fk', to='pj_app.User'),
        ),
        migrations.AddField(
            model_name='mprun',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.Proj'),
        ),
        migrations.AddField(
            model_name='mprun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.User'),
        ),
        migrations.AddField(
            model_name='mpjson',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.MpRun'),
        ),
        migrations.AddField(
            model_name='module',
            name='downer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downer_fk', to='pj_app.User'),
        ),
        migrations.AddField(
            model_name='module',
            name='vowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vowner_fk', to='pj_app.User'),
        ),
        migrations.AddField(
            model_name='fmrun',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.Module'),
        ),
        migrations.AddField(
            model_name='fmrun',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.Proj'),
        ),
        migrations.AddField(
            model_name='fmrun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.User'),
        ),
        migrations.AddField(
            model_name='dcrun',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.Module'),
        ),
        migrations.AddField(
            model_name='dcrun',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.Proj'),
        ),
        migrations.AddField(
            model_name='dcrun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.User'),
        ),
        migrations.AddField(
            model_name='dcqorgroup',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.DcRun'),
        ),
        migrations.AddField(
            model_name='dcpowerrpt',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.DcRun'),
        ),
        migrations.AddField(
            model_name='dcerror',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.DcRun'),
        ),
        migrations.AddField(
            model_name='dcclkgaterpt',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.DcRun'),
        ),
        migrations.AddField(
            model_name='dcchkdsggroup',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_app.DcRun'),
        ),
    ]
