# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pj_app', '0003_auto_20170802_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcerror',
            name='run',
        ),
        migrations.RemoveField(
            model_name='dcpowerrpt',
            name='run',
        ),
        migrations.RemoveField(
            model_name='dcqorgroup',
            name='run',
        ),
        migrations.RemoveField(
            model_name='dcqorrpt',
            name='group',
        ),
        migrations.RemoveField(
            model_name='dctimerpt',
            name='run',
        ),
        migrations.RemoveField(
            model_name='dcwarning',
            name='run',
        ),
        migrations.DeleteModel(
            name='DcError',
        ),
        migrations.DeleteModel(
            name='DcPowerRpt',
        ),
        migrations.DeleteModel(
            name='DcQorGroup',
        ),
        migrations.DeleteModel(
            name='DcQorRpt',
        ),
        migrations.DeleteModel(
            name='DcTimeRpt',
        ),
        migrations.DeleteModel(
            name='DcWarning',
        ),
    ]
