# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_app', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
