# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_app', '0006_auto_20170816_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='pub_time',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
