# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pj_app', '0007_auto_20170816_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
