//
//  auto generated by mux_sel.py
//

// wire declaration
{%-for wire_name in wire_lst%}
  wire {{wire_name}};
{%-endfor%}

// assignments
{%-for assign_key, assign_value in assign_dic|dictsort%}
  assign {{assign_key}} = {{assign_value}};
{%-endfor%}
